/* Datos para la tabla AUTORES de la base de datos LIBRERÍA */
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'José Saramago','1','www.josesaramago.org');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Arturo Pérez Reverte','2','www.perezreverte.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Stieg Larsson','3','www.serielarsson.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'César Aira','4',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Antonio Muñoz Molina','2','www.antoniomuñozmolina.es');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Javier Marías','2','www.javiermarias.es');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Alice Munro','5','www.alicemunro.ca');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Mario Vargas Llosa','6','www.mvargasllosa.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Muriel Barbery','7',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Fernando Vallejo','8',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Carlos Ruiz Zafón','2','www.carlosruizzafon.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Stephen King','9','www.stephenking.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Ken Follet','10','www.kenfollett.es');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Julian Barnes','10','www.julianbarnes.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Paulo Coelho','11','www.paulocoelho.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Dolores Redondo','2','www.doloresredondomeira.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Blue Jeans','2','www.lawebdebluejeans.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Daniel Kahneman','9',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Patrick Rothfuss','9','www.patrickrothfuss.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'George R. R. Martin','9','www.georgerrmartin.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Jonas Jonasson','3',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'John Green','9','www.johngreenbooks.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Dan Brown','9','www.danbrown.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Suzanne Collins','9','www.suzannecollinsbooks.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Veronica Roth','9',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Megan Maxwell','2','www.megan-maxwell.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Markus Zusak','12',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Brandon Sanderson','9','www.brandonsanderson.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Corina Bomann','13',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `IdNacionalidad`, `Web`) VALUES (null,'Anne Rice','9','www.annerice.com');
