/* Datos para la tabla AUTORES de la base de datos LIBRERÍA */
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'José Saramago','Portuguesa','www.josesaramago.org');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Arturo Pérez Reverte','Española','www.perezreverte.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Stieg Larsson','Sueca','www.serielarsson.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'César Aira','Argentina',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Antonio Muñoz Molina','Española','www.antoniomuñozmolina.es');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Javier Marías','Española','www.javiermarias.es');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Alice Munro','Canadiense','www.alicemunro.ca');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Mario Vargas Llosa','Peruana','www.mvargasllosa.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Muriel Barbery','Francesa',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Fernando Vallejo','Mexicana',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Carlos Ruiz Zafón','Española','www.carlosruizzafon.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Stephen King','Estadounidense','www.stephenking.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Ken Follet','Británica','www.kenfollett.es');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Julian Barnes','Británica','www.julianbarnes.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Paulo Coelho','Brasileña','www.paulocoelho.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Dolores Redondo','Española','www.doloresredondomeira.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Blue Jeans','Española','www.lawebdebluejeans.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Daniel Kahneman','Estadounidense',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Patrick Rothfuss','Estadounidense','www.patrickrothfuss.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'George R. R. Martin','Estadounidense','www.georgerrmartin.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Jonas Jonasson','Sueca',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'John Green','Estadounidense','www.johngreenbooks.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Dan Brown','Estadounidense','www.danbrown.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Suzanne Collins','Estadounidense','www.suzannecollinsbooks.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Veronica Roth','Estadounidense',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Megan Maxwell','Española','www.megan-maxwell.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Markus Zusak','Australiana',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Brandon Sanderson','Estadounidense','www.brandonsanderson.com');
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Corina Bomann','Alemana',null);
INSERT INTO `autor`(`IdAutor`, `Nombre`, `Nacionalidad`, `Web`) VALUES (null,'Anne Rice','Estadounidense','www.annerice.com');
